//
//  QuizViewController.swift
//  BrainQuiz
//
//  Created by Justin Matsnev on 9/30/15.
//  Copyright © 2015 Justin Matsnev. All rights reserved.
//

import Foundation
import UIKit

class QuizViewController : UIViewController, UITextFieldDelegate {
    
    @IBOutlet var answerField : UITextField!
    var array : Array<String>!
    var vocabArray : Dictionary = ["brain":"an organ of soft nervous tissue contained in the skull of vertebrates, functioning as the coordinating center of sensation and intellectual and nervous activity.","nuerotransmitter":"a chemical substance that is released at the end of a nerve fiber by the arrival of a nerve impulse and, by diffusing across the synapse or junction, causes the transfer of the impulse to another nerve fiber, a muscle fiber, or some other structure.","fMRI":"(functional MRI)combo of MRI and pet scan","Phrenology":"history of the mind","Franz Gill":"scientist in 1800's; suggested that bumps on the skull represented mental abilities. His theory was not valid but proposed that different mental abilities were modular.","neuron":"a nerve cell that consists of many different parts","Cell Body":"cell's life support center","Dendrites":"bushy, branching extensions that receive messages from other cells","Axon":"passes messages away from the cell body to other neurons, muscles, or glands","Neural Impulse":"electrical signal traveling down the axon","Terminal branches":"form junctions with other cells","Myelin Sheath":"covers axons of some neurons and helps speed neural impulses","sensory neurons":"run from the various types of stimulus receptors including touch, odor, taste, sound, vision","interneurons":"found exclusively within spinal chord and brain","motor neurons":"transmit impulses ( send messages from the central nervous system to muscles and glands)","glial cells":"hold neurons together, supports and serves as a protector of neurons, removes waste, allows them to work more efficiently. There are more of these than neurons.","Action Potential":"a brief electrical charge that travels down an Axon and generated by the movement of positively charged atoms in and out of channels in the axons membrane","Ions":"exchange of electrically charged plus & minus atoms","reflex":"simplest form of neural transmission; efferent and afferent nerve fibers fire messages to your spinal cord and brain to kick for example","synapse":"a junction between the axon tip of the sending neuron and the dendrite or cell body of the receiving neuron.","Refractory Period":"after a neuron fires an action potential it pauses for a short period to recharge itself to fire again.","Sodium-potassium pump":"pump positive ions out from the inside of the neuron, making them ready for another action potential.","Acetylcholine (ACb)":"enables muscle action, learning, and memory","Dopamine":"influences movement, learning, attention, and emotion","Serotonin":"affects mood, hunger, sleep, and arousal.","norepinephrine":"helps control alertness and arousal.","Gaba":"a major inhibitory neurotransmitter","Glutamate":"major excitatory neurotransmitter involved in memory","reuptake":"in this process , neurotransmitters in the synapse are reabsorbed into the sending process. This applies the breaks on neurotransmitter action","Brainstem":"oldest part of the brain, where the spinal cord swells and enters the skull. Responsible for automatic survival functions","Thalamus":"the brains sensory switchboard located on the top of the brain stem. If directs messages to the sensory areas in the cortex and transmits replies to the cerebellum and medulla","Cerebellum":"the little brain attached to the rear of the Brainstem","Limbic System":"doughnut shaped system of neural structures at the border of the Brainstem and cerebellum, associated with emotions such as fear, aggression, and drives for food and sex","Medulla":"base of the Brainstem that controls heartbeat and breathing","Reticular formation":"nerve network in Brainstem that plays an important role in controlling arousal","Amygdala":"consists of two almond shaped neural clusters linked to fear and anger","Hypothalamus":"lies below the thalamus. Directs several maintenance activities like eating, drinking, body temp, and control of emotions. Helps govern the endocrine system via the pituitary gland.","Nervous System":"consists of all the nerve cells. It is the bodies speedy electrochemical communication system","Central Nervous System (CNS)":"brain and spinal cord", "Peripheral Nervous System (PNS)":"the sensory and motor neurons that connect the central nervous system to the rest of the body"]
    override func viewDidLoad() {
        answerField.delegate = self
//        querying("https://api.quizlet.com/2.0/sets/95583670?client_id=Szf5zdUGnc&whitespace=1")
        textFieldDidBeginEditing(answerField)
        textFieldDidEndEditing(answerField)
        textFieldShouldReturn(answerField)
    }
    
//    func querying(urlString : NSString) {
//        let url = NSURL(string: urlString as String)
//        let task = NSURLSession.sharedSession().dataTaskWithURL(url!) {(data, response, error) in
//            let jsonResult: NSDictionary = (try! NSJSONSerialization.JSONObjectWithData(data!, options: NSJSONReadingOptions.MutableContainers)) as! NSDictionary
//            if error == nil {
//                // print("data is:")
//                let allTerms : NSArray = jsonResult["terms"]! as! NSArray
//                for eachTerm in allTerms {
//                    let termAsDict : NSDictionary = eachTerm as! NSDictionary
//                    let eachValueof5 = termAsDict.allValues
//                    self.vocabArray.addObject(eachValueof5)
//                    
//                    
//                }
//                
//                
//            }else{
//                if let err:String? = String(error?.description){
//                    print("faced to this error: \(err)")
//                }
//            }
//        }
//        task.resume()
//    }
    
    
    
    func textFieldShouldReturn(textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
    
    func textFieldDidEndEditing(textField: UITextField) {
        //move textfields back down
        UIView.beginAnimations( "animateView", context: nil)
        var frame : CGRect = self.view.frame
        frame.origin.y = 0
        self.view.frame = frame
        UIView.commitAnimations()
        
    }
    
    func textFieldDidBeginEditing(textField: UITextField) {
        
        //move textfields up
        let myScreenRect: CGRect = UIScreen.mainScreen().bounds
        let keyboardHeight : CGFloat = 216
        
        UIView.beginAnimations( "animateView", context: nil)
        var needToMove: CGFloat = 0
        
        var frame : CGRect = self.view.frame
        if (textField.frame.origin.y + textField.frame.size.height + /*self.navigationController.navigationBar.frame.size.height + */UIApplication.sharedApplication().statusBarFrame.size.height > (myScreenRect.size.height - keyboardHeight)) {
            needToMove = (textField.frame.origin.y + textField.frame.size.height + /*self.navigationController.navigationBar.frame.size.height +*/ UIApplication.sharedApplication().statusBarFrame.size.height) - (myScreenRect.size.height - keyboardHeight);
        }
        
        frame.origin.y = -needToMove
        self.view.frame = frame
        UIView.commitAnimations()
        
    }
    
    
}